### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by tgeens** [AlfrescoLabs/technical-validation#65]
The latest release dates from Nov 2014. Can we have a new release, please ?

**Comment by pmonks** [comment]
@Marina-Alfresco it is considered poor etiquette to close issues without an explanation. Can you please explain why this (and other) issues have been closed?

[edit] oh and hi 👋  @tgeens! I hope you're well! 😉

**Comment by ghost** [comment]
Hi @pmonks apologies for the lack of comment. I understand these repositories are not supported by the Alfresco team and as such as I am closing the issues.

**Comment by pmonks** [comment]
@Marina-Alfresco how does a lack of support equate to the issues being invalid though?  Surely preserving the issues so that the community knows they exist and can perhaps address them has value?

**Comment by ghost** [comment]
fair point, reopened them all.

**Comment by pmonks** [comment]
@Marina-Alfresco if you're interested, the history is that the `AlfrescoLabs` GH org was created largely to create a clear separation between official supported product, and Alfresco-employee developed/maintained, but _not_ supported, projects.

Source: I was an Alfresco employee at the time, and involved in the discussions & decision that led to the creation of the org (along with @LuisSala, @uzquiano, @jottley and others).

**Comment by ghost** [comment]
Hi @pmonks , yeah I knew about the history and what I am trying to do is to revamp that idea (this instance has been very quiet). I am starting with organising the main Alfresco Github instance and even moving 'experiments' that were added in that instance to here. The plan is for that one to be only for supported code and this one for the unsupported experiments. 
Hopefully once I finished that one and move to reignite this one, it will become more active :)

**Comment by pmonks** [comment]
Nice!  Yeah that was always the intent, though I'm not surprised to hear that over time experiments have trickled into the main Alfresco org - it was inevitable really, without ongoing curation.
